### ISSUE TITLE
Sagemath Cloud API

### ISSUE THREAD

**Issue by PeterBocan** [sagemath/cloud#101] opened 2014-02-16 12:27 UTC
Hello folks, it would be really nice to have access to projects (and files) stored on the cloud. Upload/Download/Execute files on the cloud. 

That's a bit rough estimate what it should/could do.

**Comment by haraldschilly** [comment] 2016-04-07 09:15
possible duplicate of #60

**Closed by haraldschilly** 2016-04-07 09:15 UTC

**Comment by Eulerianial** [comment] 2016-05-05 10:22
Harald, so this work is in progress. Am I right?

**Comment by haraldschilly** [comment] 2016-05-05 10:25
this ticket is closed, so no. there above your comment is a pointer to #60 ... but so far that's all rather vague. What would be your use case or why are you asking?
